### ISSUE TITLE
VM error running first_run.sh

### ISSUE THREAD

**Issue by DANAJK** [CCPPETMR/CCPPETMR_VM#71]
Running `first_run.sh`, I get:
`sirfuser@ubuntu-xenial:~$ ~/devel/CCPPETMR_VM/scripts/first_run.sh
dd: error writing '/tmp/EMPTY': No space left on device
5683+0 records in
5682+0 records out
5958332416 bytes (6.0 GB, 5.5 GiB) copied, 17.1617 s, 347 MB/s`

**Comment by KrisThielemans** [comment]
you shouldn't have to run this normally. Edo will do this at creation time for the next VM. However, of course you should be able to run it.

It turns out that this message is expected. The zerofill trick first creates a file that fills up everything (by runnign ot of disk space), and then removes it. This is ONLY useful for then exporting the VM. Otherwise, what it will do is expand the virtual disk to actually occupy quite a lot of disk space on your HD.

@paskino, can you document the usage of `first_run.sh` in the README? Also, I guess it's best that you have something like the following before the `dd` statement
```bash
echo "Now creating a very large file filled with zeroes, and then delete it"
echo "such that VirtualBox will create a compact OVA file."
echo "You will see message saying \"error writing '/tmp/EMPTY'\". This is expected."
```

**Comment by KrisThielemans** [comment]
ah. I see that this confusion is caused by @paskino adding  step 6 on first_run.sh in INSTALL.md. This seems incorrect. The user doesn't have to do this. Instead, this step has to be in the instructions in our README.md on how to create the VM I believe.
